name: educsa
description: "Aplicativo de comunicação do Colégio Santo Antônio."
publish_to: 'none' 
version: 1.0.0+4

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.0
  http: ^1.2.1
  mask_text_input_formatter: ^2.5.0
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  image_picker: ^1.1.2
  table_calendar: ^3.2.0
  url_launcher: ^6.2.6
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/educsaicon.png"
  remove_alpha_ios: true